### PR TITLE
[release-script]Update sampleapp download script

### PR DESCRIPTION
**Pull request by qiuzhong**
Update the sampleapp download script to avoid error when running the
script for the second time. This is need for packing test suites of nw.js.

### CODE REVIEW

**Comment by qiuzhong** [comment]
@Honry

**Comment by Honry** [comment]
Pls. provide the UT result.

**Comment by qiuzhong** [comment]
Tested and the sampleapp repos update is verified.

**Comment by Honry** [comment]
Thanks, LGTM.

**Pull request merged**
